from pathlib import Path

ENCODING = "utf-8"
HEADER_SIZE = 4
MAX_PAYLOAD_SIZE = 1024 * 1024
RECV_CHUNK_SIZE = 4096
MAX_APPLICATION_PAYLOAD_SIZE = 128 * 1024
MAX_METADATA_SIZE = 4096
MAX_METADATA_FIELDS = 16
MAX_TEXT_MESSAGE_CHARS = 4096
MAX_CIPHERTEXT_BYTES = 64 * 1024
MAX_CONTENT_TYPE_LENGTH = 80
MAX_INBOX_MESSAGES = 50
MAX_ACK_MESSAGE_IDS = 100
MAX_REQUEST_ID_LENGTH = 64
MAX_ACTION_LENGTH = 64
MAX_USERNAME_LENGTH = 32
MESSAGE_ID_HEX_LENGTH = 32
SESSION_ID_HEX_LENGTH = 32
PREKEY_ID_HEX_LENGTH = 24

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 65432
SOCKET_BACKLOG = 20

MESSAGE_TYPE_REQUEST = "request"
MESSAGE_TYPE_RESPONSE = "response"
MESSAGE_TYPE_EVENT = "event"

STATUS_OK = "ok"
STATUS_ERROR = "error"

DEFAULT_MESSAGE_CONTENT_TYPE = "text/plain"
E2EE_MESSAGE_CONTENT_TYPE = "application/e2ee+json"
E2EE_MESSAGE_VERSION = 1
E2EE_SESSION_MESSAGE_VERSION = 2
E2EE_ENCRYPTION_SUITE = "X25519+HKDF-SHA256+ChaCha20-Poly1305"
E2EE_SESSION_ENCRYPTION_SUITE = "SessionX25519+HKDF-SHA256+ChaCha20-Poly1305"
E2EE_SIGNATURE_ALGORITHM = "Ed25519"
SESSION_INIT_MODE_STATIC = "static_x25519"
SESSION_INIT_MODE_REPLY_PREKEY = "reply_prekey_x25519"
SESSION_HEADER_TYPE_INIT = "init"
SESSION_HEADER_TYPE_EXISTING = "existing"
SESSION_MAX_MESSAGES = 5
SESSION_TTL_SECONDS = 1800
SESSION_MAX_SKIP = 32
MESSAGE_STATUS_PENDING = "pending"
MESSAGE_STATUS_DELIVERED = "delivered"

ACTION_REGISTER = "register"
ACTION_LOGIN = "login"
ACTION_LOGIN_INIT = "login_init"
ACTION_LOGIN_FINISH = "login_finish"
ACTION_LOGIN_CANCEL = "login_cancel"
ACTION_GET_USER_KEYS = "get_user_keys"
ACTION_ADD_CONTACT = "add_contact"
ACTION_LIST_CONTACTS = "list_contacts"
ACTION_ONLINE = "online"
ACTION_SEND = "send_message"
ACTION_INBOX = "inbox"
ACTION_ACK_INBOX = "ack_inbox"
ACTION_EXIT = "exit"

EVENT_INCOMING_MESSAGE = "incoming_message"
LOGIN_CHALLENGE_EXPIRATION_SECONDS = 120

PROJECT_ROOT = Path(__file__).resolve().parents[1]
CLIENT_DATA_DIR = PROJECT_ROOT / "client" / "data"
CLIENT_KEYS_DIR = CLIENT_DATA_DIR / "keys"
CLIENT_SESSION_DIR = CLIENT_DATA_DIR / "sessions"
CLIENT_TLS_DIR = CLIENT_DATA_DIR / "tls"
TRUSTED_SERVER_CERT_FILE = CLIENT_TLS_DIR / "trusted_server_cert.pem"
TRUSTED_SERVER_FINGERPRINT_FILE = CLIENT_TLS_DIR / "trusted_server_fingerprint.txt"
SERVER_DATA_DIR = PROJECT_ROOT / "server" / "data"
USERS_FILE = SERVER_DATA_DIR / "users.json"
MESSAGES_FILE = SERVER_DATA_DIR / "messages.json"
SERVER_CERT_FILE = SERVER_DATA_DIR / "server_cert.pem"
SERVER_KEY_FILE = SERVER_DATA_DIR / "server_key.pem"
